remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
title: League of Legends Early Game Objectives Statistical Analysis
description: An analysis of how early game objectives influence match outcomes in professional League of Legends games.
show_downloads: false 